# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Expert interface
#'
#' @description For experts that are familiar with the C API of the underlying
#'   \code{libswe}, an expert interface that mimicks that interface as closely
#'   as possbile is provided.
#' @param jd  Julian date as numeric vector
#' @param t_acc tidal acceleration as double (arcsec/century^2)
#' @param tjd  Julian day Number
#' @param file  the directory plus file (a string)
#' @param geolon  Topocentric Longitude (deg)
#' @param geolat  Topocentric Latitude (deg)
#' @param geopos The position vector (longitude, latitude, height)
#' @param altitude  the height (m)
#' @param delta_t DeltaT value (sec)
#' @param tjd_et  Julian day, Ephemeris time
#' @param ipl  body/planet number (-1 for no planet possible with \code{swe_rise_trans_true_hor})
#' @param iflag  a 32 bit integer containing bit flags that indicate what
#'               kind of computation is wanted
#' @param star,starname  star name ("" for no star possible with \code{swe_rise_trans_true_hor})
#' @param tjd_ut  Julian day, UT time
#' @param calc_flag Type of reference system
#' @param atpress atmospheric pressure in mbar (hPa)
#' @param attemp atmospheric temperature in degrees Celsius
#' @param epheflag Type of ephemeris (4=Moshier, 1=JPL, 2=SE)
#' @param horhgt The apparent horizon at rise/set in degrees
#' @param xin  position of body in either ecliptical or equatorial coordinates, depending on calc_flag
#' @param rsmi  integer specifying that rise, set, or one of the two meridian transits is wanted
#' @return \code{swe_rise_trans_true_hor} returns a list with named entries: \code{i} success of function
#'      \code{tret} for azi/alt info and \code{serr} for possible error code
#' @return \code{swe_azalt} returns a list with named entries:
#'      \code{xaz} for azi/alt info.
#' @return \code{swe_fixstar} returns a list with named entries \code{return},
#'         \code{star}, \code{xx}, and \code{serr} for return code, updated star name,
#'         calculated values and error message.
#' @return \code{swe_calc} returns a list with named entries \code{rc},
#'         \code{xx}, and \code{serr} for return code, calculated values
#'         and error message.
#' @return  \code{swe_deltat} returns the DeltaT (sec)
#' @return \code{swe_day_of_week} retruns the day of week as integer vector
#' @return \code{get_tid_acc} returns the tidal acceleration as double (arcsec/century^2)
#' @return \code{swe_version} returns the Swiss Ephemeris version number as string
#' @name expert-interface
NULL

#' Compute day of week
#' @rdname expert-interface
#' @export
swe_day_of_week <- function(jd) {
    .Call(`_swephR_day_of_week`, jd)
}

#' Get the present configured tidal acceleration
#' @rdname expert-interface
#' @export
swe_get_tid_acc <- function() {
    .Call(`_swephR_get_tid_acc`)
}

#' Get the Swiss Ephemeris version number
#' @rdname expert-interface
#' @export
swe_version <- function() {
    .Call(`_swephR_version`)
}

#' Set the tidal acceleration
#' @rdname expert-interface
#' @export
swe_set_tid_acc <- function(t_acc) {
    invisible(.Call(`_swephR_set_tid_acc`, t_acc))
}

#' Determine the DeltaT at a certain date
#' @rdname expert-interface
#' @export
swe_deltat <- function(tjd) {
    .Call(`_swephR_deltat`, tjd)
}

#' Set the directory for the sefstar.txt, swe_deltat.txt and jpl files
#' @rdname expert-interface
#' @export
swe_set_ephe_path <- function(file) {
    invisible(.Call(`_swephR_set_ephe_path`, file))
}

#' Set the topocentric location (lon, lat, height)
#' @rdname expert-interface
#' @export
swe_set_topo <- function(geolon, geolat, altitude) {
    invisible(.Call(`_swephR_set_topo`, geolon, geolat, altitude))
}

#' Set one's own DeltaT
#' @rdname expert-interface
#' @export
swe_set_delta_t_userdef <- function(delta_t) {
    invisible(.Call(`_swephR_set_delta_t_userdef`, delta_t))
}

#' Compute information of planet
#' @rdname expert-interface
#' @export
swe_calc <- function(tjd_et, ipl, iflag) {
    .Call(`_swephR_calc`, tjd_et, ipl, iflag)
}

#' Compute information of stars
#' @rdname expert-interface
#' @export
swe_fixstar <- function(star, tjd_et, iflag) {
    .Call(`_swephR_fixstar`, star, tjd_et, iflag)
}

#' Compute horizon information: azimuth, altitude
#' @rdname expert-interface
#' @export
swe_azalt <- function(tjd_ut, calc_flag, geopos, atpress, attemp, xin) {
    .Call(`_swephR_azalt`, tjd_ut, calc_flag, geopos, atpress, attemp, xin)
}

#' Compute the rise and set location of the object
#' @rdname expert-interface
#' @export
swe_rise_trans_true_hor <- function(tjd_ut, ipl, starname, epheflag, rsmi, geopos, atpress, attemp, horhgt) {
    .Call(`_swephR_rise_trans_true_hor`, tjd_ut, ipl, starname, epheflag, rsmi, geopos, atpress, attemp, horhgt)
}

