# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute day of week
#' @param jd  Julian date as double
#' @return Day of week as integer
#' @export
day_of_week <- function(jd) {
    .Call(`_swephR_day_of_week`, jd)
}

